- README.md
- docs/changelog.rst
- docs/conf.py
- docs/gallery.rst
- docs/how_to.rst
- docs/index.rst
- docs/quickstart.rst
- noxfile.py
- poetry.lock
- pyproject.toml
- New quickstart guide
- New how-to guide 
- New example gallery (new dev dependency - `sphinxcontrib-images`)
- Bootstrap theme for doc site (new dev dependency - `sphinx_bootstrap_theme`)
- Intro page updated  
- Minor readme changes
- Use dev mode in docs noxsession
> Revamp docs - new quickstart, how-to, gallery

- .github/workflows/tests.yml
- src/seaborn_image/_core.py
- src/seaborn_image/_filters.py
- src/seaborn_image/_general.py
- tests/test_core.py
- tests/test_filters.py
- tests/test_general.py
- `dimension` can now be specified in all plot functions
This was already implemented in [matplotlib_scalebar](https://github.com/ppinard/matplotlib-scalebar). Now available in [seaborn_image](https://seaborn-image.readthedocs.io/)
For example - 
```python
import seaborn_image as isns
isns.imgplot(data, dx=1, units="ft", dimension="imperial") # default is "si"
> Add `dimension` parameter for scale bar to all plot functions

- src/seaborn_image/_context.py
- src/seaborn_image/_core.py
- src/seaborn_image/_general.py
- tests/test_context.py
- `set_image()` function now also changes and registers seaborn-image colormaps
- default cmap is 'ice', set globally upon import
- Note : this will change the default for any matplotlib figure until `reset_defaults()`is called to set it to matplotlib default viridis. This can, of course, also be done using `set_image(cmap="viridis")`
Example:
```python
isns.set_image(cmap="acton") # use seaborn-image colormaps
isns.set_iamge(cmap="viridis") # matplotlib colormaps work as usual
> seaborn-image cmaps can now be set globally using `set_image`

- src/seaborn_image/__init__.py
- src/seaborn_image/_context.py
- src/seaborn_image/_core.py
- src/seaborn_image/_filters.py
- src/seaborn_image/_general.py
- src/seaborn_image/utils.py
- tests/test_core.py
- tests/test_filters.py
- tests/test_general.py
- tests/test_utils.py
- orientation control for colorbar in `imgplot` and `imghist`
Example:
```python
isns.imgplot(data, orientaion="h") # this will plot the colorbar horizontal 
isns.imghist(data, orientation="h") # this will plot the colorbar and the histogram horizontal
```
- despine plots by default; available as a parameter in `imgplot` and `imghist`
- `isns.despine()` also available independently
-  `isns.scientific_ticks()` : make colorbar ticks scientific
- Remove unnecessary parametrization to exponentially speed up the test suite; without significantly hurting the test coverage
> control colorbar orientation, despine by default, sci ticks

- src/seaborn_image/_general.py
- tests/test_general.py
This PR implements adds a `gray` parameter to `imgplot()` function
```python
isns.imgplot(data_rgb, gray=True)
isns.imgplot(data_2d, gray=True)
isns.imgplot(data_2d, cmap="deep", gray=True)
```
> add `gray` parameter to imgplot()

- src/seaborn_image/_filters.py
- src/seaborn_image/_grid.py
- tests/test_filters.py
- tests/test_grid.py
The following is now accepted : 
```python
>>> import seaborn_image as isns
>>> import scipy.ndimage as ndi
>>> isns.filterplot(data, ndi.gaussian_filter, sigma=5)
>>> isns.FilterGrid(data, ndi.gaussian_filter, row="sigma", sigma=[3,4,5,6])
```
Note: the `filt` parameter can be any callable filter. It also accepts `str` but only for the ones mapped in seaborn-image. You can do `isns.implemented_filters` to get the mapped filters that can be used as strings.
> `filterplot`, and by extension `FilterGrid`, now accepts any callable filter

- src/seaborn_image/_core.py
- src/seaborn_image/_filters.py
- src/seaborn_image/_general.py
- tests/test_core.py
- tests/test_general.py
Colormap range is calculated based on the percentiles defined in `perc` percentile parameter instead of the extremes when `robust` is `True`. Default `perc` range is (2,98) - 2nd and 98th percentiles for min and max values.
`robust` had been added to `imgplot`, `imghist`, `filterplot`
Example Usage:
```python
"""Exclude outliers"""
>>> isns.imgplot(data, robust=True)
"""Specify percentiles for min and max values"""
>>> isns.imgplot(data, robust=True, perc=(2, 99))
```
> Exclude outliers using `robust` parameter while plotting

- src/seaborn_image/_core.py
This PR fixes a minor bug that came about when `vmin`/`vmax` was specified with `robust` parameter in `imgplot()`
> fix `robust` state issue when `vmin`, `vmax` specified

- .github/workflows/coverage.yml
- docs/conf.py
- docs/reference.rst
- noxfile.py
- poetry.lock
- pyproject.toml
- src/seaborn_image/_context.py
- src/seaborn_image/_core.py
- src/seaborn_image/_filters.py
- src/seaborn_image/_general.py
- src/seaborn_image/_grid.py
- src/seaborn_image/utils.py
- tests/test_context.py
- tests/test_core.py
- tests/test_general.py
- tests/test_utils.py
The following have been removed from `imgplot` as well as other visualizations functions:
- `cbar_dict`
- `title`
- `title_dict`
The rationale is that if the user wants to set title for example, they can just do `ax.set_title("Title")`. There is no real need to provide this as kwarg in `seaborn_image` functions. It was anyways remnant of some old code.
<s>fftplot</s> This will be done with the `fftplot` enhancement
> Clean up imgplot kwargs, reformat docstrings to numpy style & use matplotlib plot-directive in docstring examples

- README.md
- src/seaborn_image/_filters.py
- src/seaborn_image/_general.py
- src/seaborn_image/_grid.py
- src/seaborn_image/utils.py
- tests/test_filters.py
- tests/test_general.py
- tests/test_utils.py
| Axes level | Figure level |
| --- | ----------- |
| `imgplot()` | `imghist()` |
| `filterplot()` | `FilterGrid()` |
| `fftplot()` |  |
Axes level functions only return `matplotlib.axes.Axes` and figure level functions only return `matplotlib.figure.Figure` or `seaborn_image.FilterGrid`.
> Stricter separation between axes and fig level functions

- src/seaborn_image/_general.py
- src/seaborn_image/_grid.py
- tests/test_general.py
Height and aspect ratio can now be controlled for `imghist()` function
Example:
```python
isns.imghist(img, height=4, aspect=1.5)
```
> Add `height` and `aspect` parameters to `imghist()`

- src/seaborn_image/_filters.py
- tests/test_filters.py
- Control whether `fftshift` is applied or not using the `shift` parameter
```python
isns.fftplot(img, shift=False)
```
- Specify window types from `scipy.signal.get_window`
```python
isns.fftplot(img, window_type="hann")
isns.fftplot(img, window_type=('tukey', 0.8))
```
- Update docstring and tests for `fftplot`
> upgrades to `fftplot`

- docs/reference.rst
- src/seaborn_image/_general.py
- src/seaborn_image/_grid.py
- tests/test_grid.py
This PR adds a new function `rgbplot()` which splits and plots the red, green and blue channels of an RGB image. The function returns a `seaborn_image.ImageGrid` object and is a special case of the same.
This can be done as simply as : 
```python
g = rgbplot(img)
g = rgbplot(img, cmap=["inferno", "viridis", "ice"])
```
> `rgbplot()`, as a special case of `ImageGrid()`

- examples/plot_fft.py
- examples/plot_filter.py
- examples/plot_filtergrid.py
- examples/plot_image.py
- examples/plot_image_hist.py
- examples/plot_image_robust.py
- src/seaborn_image/_context.py
- src/seaborn_image/_core.py
- src/seaborn_image/_filters.py
- src/seaborn_image/_general.py
- src/seaborn_image/_grid.py
- tests/test_context.py
- tests/test_core.py
- tests/test_filters.py
- tests/test_general.py
- tests/test_grid.py
- tests/test_utils.py
This PR adds new parameter `despine` to `set_image()` which allows global despining of image axes and colorbar axes. 
`despine` parameters in individual functions still hold (but default is now `None`) and will be given preference over global state if not specified as `None`. 
`isns.despine()` is still available for use as general utility function (Note that `isns.despine()` does not change the global state)
> despine/respine globally using `despine` parameter in `set_image()`

- pyproject.toml
- src/seaborn_image/__init__.py
- src/seaborn_image/_datasets.py
- src/seaborn_image/utils.py
- tests/test_datasets.py
- tests/test_utils.py
This PR changes the messy local path based data fetching in `load_image()`. The previous approach prohibited the use of `load_image` outside docs and repo examples. Now, uses [pooch](https://github.com/fatiando/pooch) to fetch and retrieve all data for `load_image()`.
This means calling`isns.load_image()` is no longer confined to docs and examples.
> `load_image()` can be used outside the repo scope

- docs/api/imshow.rst
- docs/index.rst
- docs/reference.rst
- src/seaborn_image/_general.py
- src/seaborn_image/utils.py
- tests/test_general.py
This is mainly for convenience - `isns.imshow` can be used instead of `isns.imgplot` with all the same arguments.
```python
import seaborn_image as inns
pol = isns.load_image("polymer")
ax = isns.imshow(polymer, dx=15, units="nm")
```
> Added `imshow` as an alias for `imgplot`

- data/README.md
- poetry.lock
- pyproject.toml
- src/seaborn_image/_datasets.py
- Closes #155 
- Added `cells.tif` to `data/` (no longer downloading from scikit-image tutorials repo; was leading some new errors?)
- Added README in `data/` 
- Updated dev dependencies
> Update min required version of `matplotlib-scalebar` to 0.7

- src/seaborn_image/_datasets.py
- tests/test_datasets.py
Changing the base url fixed the `HTTPError` that pooch was running into while downloading data
> change base url in POOCH for data retrieval

- src/seaborn_image/_grid.py
- tests/test_grid.py
Can now use different parameters for different 2D slices of 3D images while using `ImageGrid`. This was earlier only possible for a list of 2D images in `ImageGrid`
For example - 
```python
g = isns.ImageGrid(IMG_3D, cmap=["Reds", "Greens", "Blues"])
```
will return `ImageGrid` with 2D slices of 3D data plotted with different colormaps.
> Different parameters for 3D image slices in `ImageGrid`

- examples/plot_ImageGrid_map_func_list.py
- examples/plot_ImageGrid_map_func_list_to_img_list.py
- examples/plot_ImageGrid_multi.py
- examples/plot_ImageGrid_multi_map_func.py
- examples/plot_imghist_map_func.py
- src/seaborn_image/_datasets.py
- src/seaborn_image/_grid.py
- tests/test_datasets.py
- tests/test_grid.py
`ImageGrid` gains the ability to map multiple functions to the input image/s. Overall, there are 4 use cases : 
- `List` of `map_func` mapped to a `List` of 2D images
```python
g = isns.ImageGrid([img1, img2, img3], map_func=[f1, f2, f3])
```
- `List` of `map_func` applied to a single 2D image
```python
g = isns.ImageGrid(img_2d, map_func=[f1, f2, f3])
```
- Single `map_func` applied to a list of 2D images
```python
g = isns.ImageGrid([img1, img2, img3], map_func=f3)
```
- Single `map_func` applied to a 3D image
```python
g = isns.ImageGrid(img_3d, map_func=f1)
```
Parameters for individual functions can also be passed as a `Dict` or `List` of `Dict`s to `map_func_kw` parameter in `ImageGrid`
For eg - 
```python
from skimage.filters import gaussian, hessian, median
g = isns.ImageGrid( …
```
> Map multiple functions to images in `ImageGrid`

- src/seaborn_image/_context.py
- src/seaborn_image/_general.py
remove `ax` param from docstring: wasn't available in function parameters
closes #479
> fix `imghist` docstring

- src/seaborn_image/_colormap.py
- src/seaborn_image/_context.py
- src/seaborn_image/_core.py
- src/seaborn_image/_general.py
- src/seaborn_image/_grid.py
- tests/test_grid.py
The default colormaps for rgbplot were from white to red/blue/green, and it didn't show each channel properly, i added the colormaps R, G and B that go from black to red/blue/green. To do so i created a new dictionary _CMAP_EXTRA because the class of colormap present in _CMAP_QUAL was not compatible with the one i was using, if this is a problem i have no problem changing it.
The code to register the new colormaps was using a deprecated matplotlib function and was using exceptions where an if statement could be used, that is fixed now.
Now the ImageGrid class accepts a norm parameter so that logarithmic color maps can be used, however, this is implemented so all images use the same normalization, it could be a good idea to change it, but i don't think it's that important.
All the tests …
> Changed default RGB color maps and added normalization to ImageGrid

- src/seaborn_image/_context.py
The default value for `origin` is `upper` as described in [matplotlib official documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.imshow.html)
Using `lower` will make future calls on `matplotlib.plt.imshow` disaplay vertically flipped image, like this:
> Update default value for `origin`

- src/seaborn_image/_core.py
Earlier, when an `ax` was supplied, `plt.gcf()` was used to determine the figure. Now, this has been updated to use `ax.get_figure()` with `plt.gcf()` as backup.
> Update how figure is determined from supplied axis

- src/seaborn_image/_core.py
- src/seaborn_image/_filters.py
- src/seaborn_image/_general.py
- src/seaborn_image/_grid.py
- tests/test_core.py
- tests/test_general.py
I added the ability for the user to specify the 'extent' argument in functions that display images so that they can specify the coordinates where this image will be located.
This is a somewhat niche argument in the implot function implemented in matplolib that lets you specify the location of the image, it is useful when you use the basemap extension to draw the coasts of the continents on top of, for example, a pressure map. This is necessary since basemap draws the lines at certain coordinates, but, unless specified otherwise, images of size (X, Y) will always be drawn from (0,0) to (X,Y).
To ilustrate this. This is how basemap works without using the extent argument:
```
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap
import seaborn_image as …
```
> Added support for the 'extent' argument in imgplot and other functions that can make use of it

- .github/workflows/coverage.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- noxfile.py
setup-Python action on MacOS was broken after macOS latest moved to use macOS 14. 
Setup Python v5.1.1 fixes the issue
> Update setup Python action for macOS 14 compatibility

- .github/workflows/coverage.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- noxfile.py
- poetry.lock
- pyproject.toml
- Make 3.9 minimum supported Python version (3.8 is reaching EOL in Oct '24)
- Add numpy as explicit dep
- Remove 3.8 from CI tests
- Run release and coverage CI on 3.12
- Test on 3.12 for all - MacOS, Windows, Ubuntu latest
> Drop support for Python 3.8
